### ISSUE TITLE
Add a new function that renew automatically the free domain on no-ip.com periodically

### ISSUE THREAD

**Issue by bphd** [Nesos-ita/DynamicDnsUpdater#7]

**Comment by Nesos-ita** [comment]
i'm not going to implement that because they have paied version that don't expire, if you want one that is free and doesn't expire chose [desec.io](https://desec.io/) or pay noip.

**Comment by bphd** [comment]
desec seems to need to have a software running somewhere to update the IP, whereas NoIP can be updated with router softwares, needing nothing more
